name: update

on:
  schedule:
    # Every Monday at 9:00 AM ECT
    - cron: 0 14 * * 1

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - run: nix flake update
      - uses: peter-evans/create-pull-request@v5
        with:
          add-paths: flake.lock
          commit-message: "chore: Update `flake.lock`"
          delete-branch: true
          reviewers: sestrella
          title: "chore: Update `flake.lock`"
